name 'rfletcher-phantomjs'
version '0.0.1'
license 'MIT License'
summary 'A Puppet module for PhantomJS'
description 'Install or remove PhantomJS'
project_page 'https://github.com/rfletcher/puppet-phantomjs'
